# Generated by Django 4.2.5 on 2023-10-08 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logindetails',
            table='login',
        ),
    ]
